on:
  push:
    branches:
      - master

name: Github Pages Deploy

permissions:
  contents: write # for committing to gh-pages branch.

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout book sources
        uses: actions/checkout@v2 # repo checkout
        with:
          fetch-depth: 0

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1 # get rust toolchain for wasm
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install mdbook
      - run: (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.4" mdbook)

      - name: Build # build
        run: mdbook build && mdbook test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.1.7
        with:
          branch: gh-pages
          folder: book
          single-commit: true
          name: CI Deploy
